#! /bin/bash 
###########################################
#
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)
genCppPath=$baseDir/../../gen-cpp

# functions

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir
g++ -DHAVE_INTTYPES_H \
    -DHAVE_NETINET_IN_H \
    -std=c++11 \
    -Wall \
    -I/usr/local/include/thrift \
    -I$genCppPath \
    *.cpp \
    -L/usr/local/lib \
    -lthrift \
    -lthriftnb \
    -levent \
    -o server
