// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AddService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::adder;

class AddServiceHandler : virtual public AddServiceIf {
 public:
  AddServiceHandler() {
    // Your initialization goes here
  }

  int add(const int number1, const int number2) {
    // Your implementation goes here
    printf("add\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AddServiceHandler> handler(new AddServiceHandler());
  shared_ptr<TProcessor> processor(new AddServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

